### PR TITLE
Casey/form styles

### PR DESCRIPTION
**Pull request by caseytakahashi**
Styled forms!
(Esp. Course forms)

screen shot 2017-11-30 at 12 37 51 pm
screen shot 2017-11-30 at 12 38 01 pm

### CODE REVIEW

**Comment by vanesng** [comment]
@caseytakahashi these look awesome!! 👍  (:

**Comment by caseytakahashi** [comment]
Gottem

screen shot 2017-12-01 at 1 14 54 pm

**Comment by caseytakahashi** [comment]
Made sessions form look better!

screen shot 2017-12-01 at 7 51 22 pm

**Comment by caseytakahashi** [comment]
Made sessions form look better, and updated label/input colors/fontsize

screen shot 2017-12-01 at 8 03 39 pm

screen shot 2017-12-01 at 8 02 28 pm

**Pull request merged**
